### PR TITLE
URL all the things

### LINKED ISSUE #301: Why URLs
* Humans have a terrible fidelity for retaining context, process, and decision pedigree
* URLs make context time and location agnostic
  * Counters the "you had to be there, go ask Bob"-ness of most synchronous workflows 
  * Members regularly join your team mid decision or after a decision is made
  * Ability to link related concepts to prior art and ground discussions in the tangible
* URLs service as artifacts for what decisions was made, why it was made, and who made it 
* Also capture what other alternatives were considered and why they were rejected
* Giving something a URL forces the moving party to distill their ideas down to written form, to capture the essential elements of their proposal and articulate it in the clearest way possible
* "**Reduce** to writing" -> distill to what matters
* Having a URL is distinct from the scope in which something is shared. Can be URL'd to 1, 2, 100, or 6 Billion people
* Ask yourself how has your workflow changed since the cold war, if at all? Since the advent of the internet?
* What's the virtue of a URL that nobody can access other than the author? (e.g. GMail URLs)
* URL is what separates the internet from the web (concentric circles with URL on the boundary between web and internet)

See also http://ben.balter.com/2014/10/07/expose-process-through-urls/

### PR DESCRIPTION
**Pull request by benbalter**
Fixes #301.

### CODE REVIEW

**Comment by benbalter** [comment]
@bkeepers, @spraints absolutely no obligation, but if you have a free cycle to skim the post in this PR, based on our conversation in Chicago, it's still a bit rough in terms of writing, but I'd <3 your thoughts if you can spare them.

**Comment by spraints** [comment]
I like it. The first time I read through it, I got the impression that URLs would be a way to set decisions in stone. On the second read, I spent more time in the sections about what's good and what's bad, and I think those are good.

For me, one of the key values of URLs is that it helps my team to work async and distributed. There's an aesthetic angle, too: good URLs tell you what they are. And good URLs make it so that I can link right to what I'm referring to (e.g. "chat with my by going to this link" not "chat with me by downloading this app, signing in, clicking on the category 'welcome' then the topic 'new people' then finding my name in the list").

**Comment by benbalter** [comment]
> . There's an aesthetic angle, too: good URLs tell you what they are. 

I wrote about that a bit in http://ben.balter.com/2014/10/07/expose-process-through-urls/ (and went a step further, to sadly have to say that URLs link to content, which in government, isn't always true).

**Comment by benbalter** [comment]
> For me, one of the key values of URLs is that it helps my team to work async and distributed. 

You're 100% right. I tried to capture that with the idea of "preferring systems that can render organizational context time and location agnostic", breaking async into what it actually means to be async, as async can be an unintuitive concept for those not previously exposed.

**Pull request merged**
