### PR TITLE
The difference between 18F and USDS

### PR DESCRIPTION
**Pull request by benbalter**
Fixes https://github.com/benbalter/benbalter.github.com/issues/232.

### CODE REVIEW

**Comment by konklone** [comment]
**Disclosure:** commenting here in my personal capacity, and keeping the fact/opinion ratio high.

> In practice, 18F attracts the same type of West-coast talent that the PIF program was designed to attract and embodies a similar open-source-first mentality, 

Most of 18F is not from the west coast, and I think what you're aiming for there is more accurately described as just "not DC".

> but most members of 18F are in it for the long-haul, and thus are not hired for time-limited terms.

While 18F consists of full time federal government employees and are not contractors, nearly 100% of 18F employees are "direct hires" in non-competed positions, and thus have term-limited positions of 2 years, with an option to renew for another 2 years. This also describes me.

> There's a bit of nuance in how 18F maintains engagements with "client" agencies

Since 18F is not in a contractor role with the agencies it works with, the relationship is a bit more akin to "partner" rather than "client".

**Comment by benbalter** [comment]
@konklone you found the two things I was hoping to fact check before hitting the green button. Thanks for the feedback. Really appreciate the context.

Question: What's the singular and plural nouns for a member of 18F? 18Fer? e.g., Automattic has Automaticians, a GitHub we have Hubbers. Halp?

**Comment by konklone** [comment]
> Question: What's the singular and plural nouns for a member of 18F? 18Fer? e.g., Automattic has Automaticians, a GitHub we have Hubbers. Halp?

We resist your epistemological fascism and transcend your nouns. _(There is no consensus on this matter.)_

**Comment by leahbannon** [comment]
I propose you change the word "insanely" in the phrase "insanely dogmatic about working in the open" to something like "incredibly." Unless you actually think that.

**Comment by benbalter** [comment]
> I propose you change the word "insanely" in the phrase "insanely dogmatic about working in the open"

Great call. You're :100:% right. 646e4f742ae636213cb0cdc3aa33fed1ae409931

**Edit**: Wrong hash

**Comment by benbalter** [comment]
@konklone @leahbannon thanks again for your eagle-eye fact checking. Very greatly appreciated.

Hoping to :ship: tomorrow when I'm not competing with the Nats :baseball: :smile:.

**Pull request merged**
