### PR TITLE
Update Remark

### PR DESCRIPTION
**Pull request by benbalter**
@wooorm Trying to follow the lead of your increadibly helpful PR over in https://github.com/benbalter/jekyll-style-guide/pull/31, but seem to be running into two issues, if you have a second to take a look (glad to open an issue if you prefer):

1. No matter what I do, unordered lists are converted to `-`, even if I set plugins to `[]`.
2. `[^1]:` style footnotes are converted to `[^1]&#x3A;`, again, even if I set plugins to `[]`.

I assume I'm doing something wrong, but if you could point me in the right direction, I'd love to get the latest version running! :smile:

### CODE REVIEW

**Comment by wooorm** [comment]
Sure, no problem!

On `jekyll-style-guide`, you’re running remark only with its linting capabilities, no markdown is written, so the input files are not transformed.

Here on your site, you are running remark with `--output`, which means the markdown is touched: formatted, and written out. Your old `.remarkrc` has a `settings` field next to `plugins`, which defines that (list-item) bullets should use asterisks (`"bullet": "*"`), but in this commit you’ve dropped the whole settings configuration.

So, to fix both your problems, set `"settings": {"bullet": "*", "footnotes": true}`!

Does that help? Feel free to ping me if you run into more stuff, I’d gladly help!

👋

**Comment by benbalter** [comment]
Wow. Classic RTFM. Thanks for taking the time to explain anyway. Adding the settings back in (I thought for some reason the new format passed those arguments via the plugin array but suspect now they go to remark core). Really appreciative for all your great projects. Next up is looking into remark-retext!

**Comment by wooorm** [comment]
Oh yeah it’s no problem! There’s a lot of manuals to read 😉

I’m moving some settings away to plug-ins, but haven’t done everything yet (e.g., footnotes will probably be a plugin in the future)!

remark-retext and the retext ecosystem is pretty cool! I trust you’ve seen the [prose set-up for GH the guides](https://github.com/github/opensource.guide/blob/f33ea554ed678fde780ec28d60c434bca0058d9c/test/prose#L65-L85)?

**Comment by wooorm** [comment]
I investigated the spell-checking results on your posts, and found the below list of warnings (sorted and unique’s):

<details>
<summary>Speling results (total: 989)</summary>

```txt
'50s
'70s
'80s
'90s
.aligncenter
.alignleft
.alignright
.docx
.govs
.md
10MB
10px
10x
1654A
18F
18F's
18Fs
1960s
1970s
1980s
1990s
1px
1s
2d
30m10s
37Signals
3D
404s
500MB
50x
53A
552a
65x
8x
99s-problem-space
99s-requirements-in-advance
9x
AGPL
AIMD-93
APIs
ATO
ATOs
AWS
ActiveX
AddThis
Airbnb's
Akamai
Alleman
Analytics
AnchorJS
Anil
Architected
Arquillian
Ashlock
Auth
Autoblog
Automattic
BDFL
BLS
BRPAPERS
Balasubramaniam
Balter
Bao
Basecamp
Beermann
Benkler
Berne
Betanews
Bienvenidos
Bikeshed
Bikeshedding
Bjørnvig
Blackberrys
Blindspot
Blitzer's
Bluehost
Bluehost's
Brin
Brita
Bucci
Buller
ButHonestlyMonica
Byrne
CAMPAN
CC0
CCing
CD-ROMs
CDN
CDNs
CFOs
CFPB
CFPB's
CIO
CIO's
CIOs
CKAN
CMS
CMS's
CMSs
COTRs
CRM
CSI
CSS
CSS1
CSV
CSVs
CTO
CTRL-C
CTRL-F5
CTRL-V
CUNY
CYA
CYA-URL
Cao
Carfax
Carlstrom
Catriona
Chabrow
ChatOps
Cheng
Chupacabra
Cibinic
Citizen-centric
Claritin
CloudFront
Cobell
Cofounder
ColdFusion
Colum
Comcast
Comcast's
Commc'ns
Comms
Computering
Conklin
CooksSource
Coplien
Corillian
Cradas
Crim
CrushIQ
Cusumano
CxOs
Cyber
CyberDuck
Cybersecurity
DLT's
DM
DMV
DNS
DOI
DRM
Dat
Datasets
DeShaney
Deliverables
Deloitte
Dep't
Dep'ts
Dev.
Diaz
Disqus
Disruptor
DoD
Documentum
DropBox
Drupal
Drupal's
Drush
EC2
ECIPE
ESRI
Edelman
EditFlow
Elin
Embedly
Encycleopedia
Erlewine
EvilRank
FIPS
FIPS-199
FISM
FISMA
FISMA-compliant
FISMA-mandated
FISMAs
FOIA
FY2011
Fanin
Fed50
FedRAMP
FedRAMP's
FedScoop
FedScoop's
Feist
Feldman
Filetype
Fisma
Flickr
Fn
Fogel
Fordham
Foundationally
Frenemies
Fruth
GIFs
GMail
GMail's
GPL
GPLv2
GSoC
GW
GW's
GWToday
Gantt
Gardels
Gaudio
Gaudio's
Gawker's
GeoJSON
Geocities
Geolocation
Gershowitz
Gershowitz's
Gertrud
GitHubber
GitHubbers
Github
Gmail
Godbout
GovCloud
GovSpeak
GovWin
Govs
Grance
Griggs
Groupon
Groupon's
Gunn
Gwanhoo
HTML5
HTTPS
HTTPS-backed
HTTPs
Hackathons
Hadoop
Hamid
Harv.
Hearn
Henke
Heroku
Hindley
Hord
Hosuk
Hubbers
Hubberversaries
Hubot
ICT
IDIQ
IIS
IM
IMAP
IMB
IPs
IPv6
IRL
ISPs
IT-centric
ITAR
ITMRA
ITU
Iceeey
Incentivizing
Interop
Interoperability
Issa
Issuances
JS
JSON
JSONP
JST
Jailbreaking
Jairs
Jaquith
Javascript
JekyllBot
Jen
JetPack
Jetpack
Joomla
Joomlas
Jorbin
JudithGriggs
KML
Kaiyuan
Keneally
Kesan
Kime
Kirkendale
Kominers
Kundra
LAMPD
LDAP
Lampton
Lan
Lee-Makiyama
Lefkowitz
Linch
Linkable
LinkedIn
Linters
LivingSocial
LivingSocial's
Lycett
MD5
MIS
MSDN
MSNBC
Mackup
Maily
Mashable
McDonalds
Mechling
Mell
Mgmt
Mgmt.
Microcache
Microeconomic
Mikey
Minitest
Miniwatts
Mitcho
MongoDB
Mou
Mullenweg
Multisite
MyGov
MySQL
Myspace
NGO
NIST
NIST's
NPM
Nacin
Nacin's
Napa
Nawyn
Nester
NetIQ
Nginx
Non-techincal
Nordstom
Nordstrom
OAUTH
OAuth
OFAC
OMBs
OSI-approved
OSS
OSTP's
Oauth
Octocat
Octokit
Octokittens
Onboarding
Orszag
Ouyachi
Overal
PDFs
PHP
PHP's
PIA
PIAs
PIF
PIFs
PII
PRA
Pandoc
Panetta
Penenberg
Personalization
Pinkney
Piwik
PollDaddy
Poppendieck
Pre-Flight
Preston-Werner
Proc
Procedurally
Proofer
README
READMEs
RFP
RFPs
RFQ
RFQs
RPC-like
RSS
Ra11y
Rackspace
Rajiv
Ramesh
Rapportive
Revisionary
Revisioning
Riojadirecta
Riojadirecta's
Rosenfeld
Roundtable
Rubix
Rubix-cube-style
RubyGems
SAML
SCA
SDKs
SEO
SES
SMS
SORN
SP1
SSL
SaaS
Salesforce
Schrage
Schwab
Servs
Shahid
Shapefile
Shapefiles
SharePoint
SharePoints
ShareThis
Sharedaddy
Sharedaddy's
Sharepoint
Shortcode
Shyu
Sinatra-auth-GitHub
Smilin
Snowe
Soakers
Socrata
SparklePrincess87
StackOverflow
Stratcom
Subcomm.
Szalvay
TLS
TOS
TPS
TTFC
TechCrunch
TechCrunch's
TechDirt
TeleTech
Telecomm
Templating
TextWrangler
Texturize
Thinkpad
Thunderdome
TinyMCE
Tipton
Tomayko
TopoJSON
Transactional
Tricare
TwitterFeed
UI
UI/UX
URI
URL-centric
USC
USDS
USDS's
UX
Uber
Ukman
Unported
Uploader
Uptime
UserVoice
V8
VAs
VBA
VCS-ignored
VPN
Vijayan
Vivek
Vololkh
W3
W3C
WESCON
WIP
WL
Warshak
Waterfall-ish
WebOS
Weidong
WestLaw
WikiLeaks
Wilshusen
WinSCP
Wireframe
Wittow
WordPerfect
WordPress
WordPress's
WordPress-GitHub
WordPress-based
WordPressDC
Wyden
XML-RPC
XP
Xfinity-delivered
Xia
YAML
Yochai
Za
Zach
Zenefits
Zombo
Zoolander
Zuckerberg
add-ons
agency-technical-contacts-cotrs-must-learn-best-practices-in-agile-project-management
agencys
agile-engenders-a-lack-of-specificity-pre-award-rendering-cost-estimates-difficult-to-calculate
albiet
ambgiuity
amd
amongst
analyists
analytics
apache
api
approriate
architected
architecting
arrestee's
articlelD=210602225
articulable
asker
astroturf
automatted
autosave
backdoors
backend
backtrace
badass
badging
bajillion
balancer
barcode
belochkavita
belochkavitaLast
benbalter
benbalter-centric
benchmarked
bikeshed
blanche
blogosphere
blowback
bona
bonafide
bootcamp
brainer
browsable
browserwrap
brutalist
bucketizing
bulleted
bureacuracy
carbonite
carte
ccc
centricity
chanels
changelog
changeset
checkable
checkboxes
checkin
checkins
cheerleading
citizen-centric
citizen-centricity
clickwrap
cloud-centric
cludgy
codebase
cofounder
commenter
commenters
commiting
commoditized
componentized
computering
config
consumerization
consumerized
consumerizes
contribue
copyediting
cos-and-cotrs-require-education-before-agile-can-be-introduced-to-the-federal-contracting-environment
counterintuitive
cowork
crowdsourced
cryptographic
curation
customer-centric
customizable
cyber
cyber-norm
cyberattack
cybersecurity
d'être
data-proofer-ignore
datacenter
datacenters
datapoint
datapoints
dataset
datasets
datastore
de
decisional
decreeable
decrypt
deemphasis
definitional
deliverables
deprioritized
desktop-centric
developer-centric
digi-tarnished
disaggregated
disambiguates
disasterous
discoverability
discoverable
disincentived
disproven
dissatisfactory
dministrative
docuemntation
dogfood
dogfooding
doingitwrong
dotfiles
downscope
dropbox
dropdown
duplicative
e2
ecommerce
eleventy
endfor
endorcement
endunless
ensnarl
enterprise-centric
et
excerpter's
extensibility
externalities
facie
facto
faire
fallbacks
favicon
fide
filetype
finess
firehose
fixies
flaks
fooding
foundational
franca
frat-boy-esq
freemium
frontmatter
frusting
gdal
geekery
geoJSON
geodata
geospatial
gile
github
gossip-centric
governmentwide
guerilla
hackable
hackathon
hackeres
haz
heartedness
high-fidelty
highly-techincal
hoc
homebrew
html
http
human-centric
i18n
iGoogle
iceeey
ideation
immagine
impactful
implementers
incentivize
incentivized
incentivizes
incongruence
incongruencies
indiscrete
informercials
infos
infringer
initative
inoperably
instantanous
intelectual
intentioned
internet-centric
interneting
internets
internety
interoperability
interoperable
intra-
istorically
itsel
iven
jQuery
jQuery's
js
judgement
jure
just-posted-to-hacker-news-yeterday
keyless
kickass
kidz
knowhow
labyrinthian
laissez
laissez-faire
lawyered
lawyering
lessoning
libre
license-centric
lifecasters
lifecycle
lingua
linkable
linter
linters
litteral
livestream
lookups
lynchpin
managment-point-of-view
masse
meatspace
memesters
merchantability
mergable
meta-dogfooding
microcache
microsites
mid-1990s
middleware
millennials
minimis
minimus
misconfigurations
misconfigured
mistyped
moar
modularity
modularly
modus
mortem
multisite
natively
nay-sayer
nelected
new-fangled
nitty-gritty
no-brainer
no-brainers
non-WordPress
non-decisional
non-evented
non-linkable
non-negligble
nothign
née
ogr2ogr
olde
on-prem
onboard
onboarded
onboarding
onramp
operandi
operationalize
operationalized
operationalizing
overengineering
overinclusive
overnment
overnment's
percieved
permalink
permalinking
permalinks
permissioning
permissionless
personalization
post-CMS
pre-Internet
pre-Yelp
pre-award
pre-deployment
pre-negotiated
pre-styled
pre-vetted
prepending
prima
print-centric
proceses
procurements
programatic
programmatically
proto-open-data-policy
proto-version
publics
rabble-rouser
raison
reactively
readme
readmes
realtime
rebaselined
rebaselining
reconsile
recrawl
recrawled
redlines
reengineered
regins
reimagination
reimagine
reimagined
reimagining
reimplementation
remised
repo
repo's
repos
repurposed
repurposing
reseller
rganizations
riggors
rights-centric
risqué
roadmap
roadmaps
rollout
rollouts
rom-com
routings
rying
résumé
sayers
scalability
scalable
screencast
se
searchable
self-fullfilling
sentance
sherpa
ship:ing
shortcodes
shortener
shoutout
signup
skillsets
skinny-jeaned
souce
sovle
spinoff
stafftools
stageside
standup
stereotypically
stuckincustoms
stymy
subpar
subscriptionn
substantiality
summer-ish
sunsetting
supercharching
superfans
swirlies
symlink
takedown
tallguy
teach-a-CIO-how-to-fish
tech-centric
technology-centric
technologyconceptual-negotiated-sourcing
telecom
templating
test-centric
text-bassed
textarea
timezones
todays
todo
todos
toolchain
toolset
totalling
trackbacks
tradeoff
trainings
transactional
transformative
trollface
un-air-conditioned
un-constrain
unapprovable
uncreative
underperformance
underserves
unecryptable
unimagined
unordered
unprogram
unsexy
unskippable
unstick
unteach
untether
untraining
untrusting
uploader
upselling
uptime
upvotes
url
useable
usecase
user-centric
userbase
v2
ven
wakeup
walkthrough
walkthroughs
warrentless
web-centric
webcal
webpages
well-intentioned
whitelisted
whitelists
whitespace
wifi
winterkanal
wireframe
wireframes
wordpress-github-sync
workspace
wovox
wp-admin
writen
www.
yet-unimagined
à
```

</details>


I mostly did this to check out if there’s stuff `retext-spell` should do, share
some tips, and to discuss Jekyll.

Some notable things:

* Jekyll/Liquid stuff isn’t parsed, making `.aligncenter` show up. we’ve had some discussion about Liquid tags regarding remark and I’m not entirely sure what to do with them as it’s a templating language and could generate markdown too...
* A lot of warnings are for words with punctuation (such as `OSI-approved`, `PHP's`, and `UI/UX`). `retext-spell` checks parts of words too, so if you’d add `OSI`, `PHP`, `UI`, and `UX` in this case to your personal dictionary, the related warnings disappear
* There’s a case of `Github` instead of `GitHub`!!! 😉
* Cases of both `CIO's` and `CIOs`
* Pluralised numbers (`1s`, `50s`, `70s`, `80s`, `90s`, `99s`, `404s`, `1960s`, `1970s`, `1980s`, `1990s`), maybe this could go in retext-spell
* times as x (`8x`, `9x`, `10x`, `50x`, `65x`), maybe in retext-spell as well?
* There’s a problem with `:ship:ing`, where it’s seen as a word, which you can ignore by adding [`retext-emoji`](https://github.com/wooorm/retext-emoji)

...and much more stuff!

Let me know if you try tackling these messages and ping me with issues that retext or retext-spell should solve!

**Comment by benbalter** [comment]
@konklone @waldoj @IanLee1521 sad/excited to say that this PR adds spelling and grammar checks to CI, so I may be adding some friction for you to contribute (but sure I'll still provide plenty of opportunities). :smile:

**Comment by benbalter** [comment]
@wooorm ✨ Found so many mistakes I didn't even know I had (and will prevent countless ones going forward. A handful of presumptive edge cases I found, if the feedback is helpful for other problems:

* Plurals of known dictionary words (I believe the docs mentioned that stemming was specifically not supported as part of nspell
* Quotes in the form of "[T]he quick brown fox..." fail retext-spell
* `*Id.*` if it's the last word of a document
* `<!--lint ignore retext-whatever-->` didn't seem to be respected

Thank you for making such great software!

**Comment by wooorm** [comment]
Awesome, this is so cool! 🎉

Happy that many stuff was found. I hope the false positives were minimal.

<details>
<summary>Response:</summary>

> * Plurals of known dictionary words (I believe the docs mentioned that stemming was specifically not supported as part of nspell

In your personal dictionary, you can choose which word to model after, here’s the related output of `man 5 hunspell`:

> ## Personal dictionary file
>
> Personal  dictionaries are simple word lists. Asterisk at the first character position signs prohibition.  A second word separated by a slash sets the affixation.
>
>     foo
>     Foo/Simpson
>     *bar
>
> In this example, "foo" and "Foo" are personal words, plus Foo will be recognized with affixes of Simpson (Foo's etc.) and bar is a forbidden word.

That doesn’t really work with abbreviated plurals though (GH, GHs), unless some word like that is already in there somewhere? 🤷‍♂️

> * Quotes in the form of "[T]he quick brown fox..." fail retext-spell

What fails? Want to open an issue?

> * `*Id.*` if it's the last word of a document

Weird! I thought that was fixed? If you have a case of that I can try and debug.

> * `<!--lint ignore retext-whatever-->` didn't seem to be respected

Hmm, it should be! The `ignore` is a bit weird, as it ignores the next markdown “node” which can be other than expected. Maybe `disable` / `enable` would work better.

Also note that you can pass the source of messages to control in the options (e.g., `source: 'remark-lint'`, or `retext-quotes`), and then in the marker itself the right ruleId (for retext-quotes: `apostrophe` or `quote`)

The `<!--lint` keyword is registered by remark-lint, but if you’d register `remark-message-control` yourself, e.g., as `ben`, you’d need to use `<!--ben ...`!

</details>

---

Again, super glad you tried it and liked it!

👋

**Comment by benbalter** [comment]
Thanks again for the thorough response.

> In this example, "foo" and "Foo" are personal words, plus Foo will be recognized with affixes of Simpson (Foo's etc.) and bar is a forbidden word.

💥 Mind blown 💥 

> Hmm, it should be! The ignore is a bit weird, as it ignores the next markdown “node” which can be other than expected. Maybe disable / enable would work better.

Good call, will give it a try

Cases for Ben to create failing test cases for / open issues if he can:

- [ ] Id. as final footnote
- [ ] Modified quotes e.g., "[T]he"

**Pull request merged**
