### PR TITLE
Relicense content under CC-BY (From CC-BY-SA-NC)

### PR DESCRIPTION
**Pull request by benbalter**
This pull request relicenses the site's content under a [Creative Commons Attribution License](http://creativecommons.org/licenses/by/3.0/). Currently the site's content is licensed under a [Creative Commons Attribution-NonCommercial-ShareAlike License](http://creativecommons.org/licenses/by-nc-sa/3.0).

There are two key differences:
- Commercial use will be allowed (so long as attribution remains intact)
- Non-copyleft - derivative works are not required to be shared under the same license terms

The reason for the move to the less restrictive license is to simplify licensing ("do whatever you want, just attribute the source") and to encourage wider reuse of the content following a few requests to republish posts elsewhere.

The following users have submitted at least minor contributions. Please chime in below if you object to the move.
- [x] @aaronjorbin ([3 contributions](https://github.com/benbalter/benbalter.github.com/commits?author=aaronjorbin))
- [x] @konklone ([3 contributions](https://github.com/benbalter/benbalter.github.com/commits?author=konklone))
- [x] @adelevie ([3 contributions](https://github.com/benbalter/benbalter.github.com/commits?author=adelevie))
- [ ] @ctbarna ([2 contributions](https://github.com/benbalter/benbalter.github.com/commits?author=ctbarna))
- [x] @parkr ([2 contributions](https://github.com/benbalter/benbalter.github.com/commits?author=parkr))
- [x] @gbinal ([1 contributions](https://github.com/benbalter/benbalter.github.com/commits?author=gbinal))
- [x] @eduardozulian ([1 contributions](https://github.com/benbalter/benbalter.github.com/commits?author=eduardozulian))
- [x] @nacin ([1 contributions](https://github.com/benbalter/benbalter.github.com/commits?author=nacin))
- [ ] @JBindelglass ([1 contributions](https://github.com/benbalter/benbalter.github.com/commits?author=JBindelglass))
- [x] @oeon ([1 contributions](https://github.com/benbalter/benbalter.github.com/commits?author=oeon))
- [x] @mikemorris ([1 contributions](https://github.com/benbalter/benbalter.github.com/commits?author=mikemorris))
- [x] @nschonni ([1 contributions](https://github.com/benbalter/benbalter.github.com/commits?author=nschonni))
- [x] @pborreli ([1 contributions](https://github.com/benbalter/benbalter.github.com/commits?author=pborreli))
- [ ] @philipashlock ([1 contributions](https://github.com/benbalter/benbalter.github.com/commits?author=philipashlock))
- [ ] @rebeccawilliams ([1 contributions](https://github.com/benbalter/benbalter.github.com/commits?author=rebeccawilliams))
- [x] @tmcw ([1 contributions](https://github.com/benbalter/benbalter.github.com/commits?author=tmcw))
- [ ] @pmaiorana ([1 contributions](https://github.com/benbalter/benbalter.github.com/commits?author=pmaiorana))

### CODE REVIEW

**Comment by konklone** [comment]
Sounds like you don't need everybody's explicit :+1:, but :+1: anyway.

**Comment by tmcw** [comment]
:+1:

**Comment by nschonni** [comment]
:+1:

**Comment by nacin** [comment]
+1

**Comment by mikemorris** [comment]
:+1:

**Comment by aaronjorbin** [comment]
+:100:

**Comment by oeon** [comment]
+1

**Comment by parkr** [comment]
:+1:

**Comment by pborreli** [comment]
:+1:

**Comment by adelevie** [comment]
+1

**Comment by benbalter** [comment]
Thanks everyone. As a token of my appreciation, please accept this animated gif of puppies wearing bowties yawning.

yellow lab puppies animated gif so cute from dianajennifere on tumblr resized for google

**Comment by gbinal** [comment]
:+1:

**Comment by eduardozulian** [comment]
A little late but :thumbsup:.

**Pull request merged**
